name: docker

on:
  push:
    branches:
      - main

env:
  DOCKER_ENV_FILE: '/home/dafoamuser/dafoam/loadDAFoam.sh'
  DOCKER_OF_ADF_BASHRC: '/home/dafoamuser/dafoam/OpenFOAM/OpenFOAM-v1812-ADF/etc/bashrc'
  DOCKER_OF_ADR_BASHRC: '/home/dafoamuser/dafoam/OpenFOAM/OpenFOAM-v1812-ADR/etc/bashrc'

jobs:
  push_to_registry:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Build and push
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u dafoam --password-stdin
        docker pull dafoam/opt-packages:latest
        docker run -i -d -u dafoamuser --name build_latest dafoam/opt-packages:latest /bin/bash
        docker export build_latest > build_latest.tar
        docker rm -f $(docker ps -a -q)
        docker rmi -f dafoam/opt-packages:latest
        docker import build_latest.tar dafoam/opt-packages:latest
        docker push dafoam/opt-packages:latest
